### ISSUE TITLE
_pickle.UnpicklingError: unpickling stack underflow

### ISSUE THREAD

**Issue by YangYanCrisp** [Chang-Chia-Chi/SaintPlus-Knowledge-Tracing-Pytorch#1]
I had trouble when I follow the readme steps to run the code, something unexpected happened when it tried to read pickle file. Have u got the same problem before? plz tell me how to solve it if u could thx!!

**Comment by Chang-Chia-Chi** [comment]
If you want to build pickle file from scratch, you have to download files from links below:
https://www.kaggle.com/its7171/cv-strategy   --  cv1_train.pickle &  cv1_valid.pickle
https://www.kaggle.com/c/riiid-test-answer-prediction/data   --  questions.csv
You have to concatenate cv1_train.pickle & cv1_valid.pickle to one pickle file by yourself. Find example code for concatenation from this kernel in block[2]: https://www.kaggle.com/maxchang0724/get-infer 
Besides, after download the file, you have to modify train_path & ques_path in "pre_process.py" and then to run the script.

An alternative and much easier way, you could just run the kernel below and download files generated. 
I've changed authority so you could run it right now:
https://www.kaggle.com/maxchang0724/get-infer  -- train_group.pkl.zip, val_group.pkl.zip, infer_groups.pkl.zip & time_dict.pkl.zip
                                                                                
If all steps above are done correctly and the problem is about reading pickle file during training, I've not encountered it. You could try this kernel to train on Kaggle platform: https://www.kaggle.com/maxchang0724/saint-training-cv-0-799-private-0-799
